[package]
name = "pulse"
version = "0.1.0"
authors = ["Connor Monks <monkslc@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
dirs = "2.0.2"
ignore = "0.4.11"
notify = "4.0.12"
plotters = "0.2.12"
rusqlite = "0.21.0"
uuid = { version = "0.8.1", features = ["v4"] }
